data_cfg:
  name: SceneFlow
  root: data/SceneFlow
  train_list: datasets/sceneflow/debug_train.txt
  val_list: datasets/sceneflow/debug_val.txt
  test_list: datasets/sceneflow/test.txt
  num_workers: 4

  transform:
    train:
      size: [ 256, 512 ]
      mean: [ 0.485, 0.456, 0.406 ]
      std: [ 0.229, 0.224, 0.225 ]
    test:
      size: [ 512, 960 ]
      mean: [ 0.485, 0.456, 0.406 ]
      std: [ 0.229, 0.224, 0.225 ]


model_cfg:
  model: CFNet
  find_unused_parameters: true
  replace_mish: true # Replace Mish with ReLU in the first 20 epochs

  base_config:
    max_disp: 256

#  # Backbone
#  backbone_cfg:
#    type: GwcNet
#
#  # VolumeCostProcessor
#  cost_processor_cfg:
#    type: GwcVolumeCostProcessor
#
#  # DispProcessor
#  disp_processor_cfg:
#    type: GwcDispProcessor


optimizer_cfg:
  solver: Adam
  lr: 0.001
  betas: [ 0.9, 0.999 ]


loss_cfg:
  - log_prefix: disp
    type: Weighted_Smooth_l1_Loss
    loss_term_weight: 1
    weights: [0.25, 0.35, 0.5, 0.5, 0.7, 1.0, 1.0, 1.4, 2]


scheduler_cfg:
  scheduler: MultiStepLR
  gamma: 0.5
  milestones: # Learning Rate Reduction at each milestones
    - 75000
    - 90000
    - 105000
    - 120000


trainer_cfg:
  save_name: CFNet_SceneFlow
  restore_hint: 0
  restore_ckpt_strict: true
  log_iter: 1
  with_test: true
  enable_float16: false
  sync_BN: true
  save_iter: 5000
  total_iter: 150000
  total_epoch: 20
  optimizer_reset: false
  scheduler_reset: false

  sampler:
    # type: BasicStereoSampler
    batch_shuffle: true
    batch_size: 1


evaluator_cfg:
  eval_func: OpenStereoEvaluator
  save_name: CFNet_SceneFlow
  restore_hint: 0
  metric:
    - d1_all
    - epe
    - thres_1
    - thres_2
    - thres_3
  restore_ckpt_strict: true
  enable_float16: false
  sampler:
    type: BasicStereoSampler
    batch_shuffle: false
    batch_size: 1
