data_cfg:
  name: SceneFlow
  root: data/SceneFlow
  train_list: datasets/sceneflow/train_val.txt
  val_list: datasets/sceneflow/val.txt
  test_list: datasets/sceneflow/sceneflow_test.txt
  num_workers: 8

  transform:
    train:
      size: [ 256, 512 ]
      mean: [ 0.485, 0.456, 0.406 ]
      std: [ 0.229, 0.224, 0.225 ]
    test:
      size: [ 512, 960 ]
      mean: [ 0.485, 0.456, 0.406 ]
      std: [ 0.229, 0.224, 0.225 ]


model_cfg:
  model: RAFT_Stereo
#  find_unused_parameters: true
  base_config:
    hidden_dims: [128, 128, 128]
    n_downsample: 2
    n_gru_layers: 3
    n_downsample: 2
    slow_fast_gru: False
    max_disp: 700
    aug_params: []
    train_iters: 12
    corr_levels: 4
    corr_radius: 4
    shared_backbone: True
    corr_implementation: reg
    # choices=["reg", "alt", "reg_cuda", "alt_cuda"]


optimizer_cfg:
  solver: Adam
  lr: 0.001
  betas: [ 0.9, 0.999 ]


loss_cfg:
  # This model uses the user-defined loss function.

scheduler_cfg:
  scheduler: MultiStepLR
  gamma: 0.1
  milestones:
    - 75000


trainer_cfg:
  save_name: RAFT-Stereo_SceneFlow_rein
  restore_hint: 0
  restore_ckpt_strict: true
  log_iter: 100
  with_test: true
  enable_float16: false
  sync_BN: true
  save_iter: 50000
  total_iter: 150000
  total_epoch: 20
  optimizer_reset: false
  scheduler_reset: false
  sampler:
    # type: BasicStereoSampler
    batch_shuffle: true
    batch_size: 4


evaluator_cfg:
  eval_func: OpenStereoEvaluator
  save_name: RAFT-Stereo_SceneFlow_rein
  restore_hint: 0
  metric:
    - d1_all
    - epe
    - thres_1
    - thres_2
    - thres_3
  restore_ckpt_strict: true
  enable_float16: false
  sampler:
    type: BasicStereoSampler
    batch_shuffle: false
    batch_size: 1
