data_cfg:
  name: SceneFlow
  root: data/SceneFlow
  train_list: datasets/SceneFlow/sceneflow_finalpass_train.txt
  val_list: datasets/SceneFlow/sceneflow_finalpass_test.txt
  test_list: datasets/SceneFlow/sceneflow_finalpass_test.txt
  # train_list: datasets/SceneFlow/debug_train.txt
  # val_list: datasets/SceneFlow/debug_val.txt
  # test_list: datasets/SceneFlow/debug_val.txt
  num_workers: 8
  train_batch_size: 4
  val_batch_size: 1
  pin_memory: true
  shuffle: true

  batch_uniform: false
  #  random_type: range
  #  w_range: [ 0.5, 2.0 ]
  #  h_range: [ 0.5, 2.0 ]
  #  random_type: choice
  #  h_range: [ 256, 288, 320, 352 ]
  #  w_range: [ 480, 512, 544, 576 ]

  transform:
    train:
      - type: FlowAugmentor
        size: [ 256, 512 ]
        min_scale: 0
        max_scale: 1.4
        do_flip: False
        saturation_range: [ -0.2, 0.4 ]
      #- type: RandomHorizontalFlip
      #  prob: 0.5
      - type: GetValidDisp
        max_disp: 192
      - type: TransposeImage
      - type: ToTensor
      - type: NormalizeImage
        mean: [ 0.485, 0.456, 0.406 ]
        std: [ 0.229, 0.224, 0.225 ]
    val:
      - type: StereoPad
        size: [ 540, 960 ]
      - type: GetValidDisp
        max_disp: 192
      - type: TransposeImage
      - type: ToTensor
      - type: NormalizeImage
        mean: [ 0.485, 0.456, 0.406 ]
        std: [ 0.229, 0.224, 0.225 ]


model_cfg:
  model: RAFT_Stereo
#  find_unused_parameters: true
  base_config:
    hidden_dims: [128, 128, 128]
    n_gru_layers: 3
    n_downsample: 2
    slow_fast_gru: False
    max_disp: 192
    aug_params: []
    train_iters: 12
    corr_levels: 4
    corr_radius: 4
    shared_backbone: True
    corr_implementation: reg
    # choices=["reg", "alt", "reg_cuda", "alt_cuda"]


loss_cfg:
  # This model uses the user-defined loss function.


trainer_cfg:
  save_name: RAFT-Stereo_SceneFlow_newright
  total_epoch: 30
  restore_hint: 0
  log_iter: 50 # iter
  save_every: 1 # epoch
  val_every: 1 # epoch
  amp: false
  sync_bn: true
  fix_bn: false
  init_parameters: false

  optimizer_cfg:
    solver: Adam
    lr: 0.001
    betas: [ 0.9, 0.999 ]

  scheduler_cfg:
    scheduler: MultiStepLR
    gamma: 0.5
    milestones: [ 5, 7, 9, 11, 15, 20]
    warmup:
      warmup_steps: 2000

  evaluator_cfg:
    metric:
      - d1_all
      - epe
      - bad_1
      - bad_2
      - bad_3

