data_cfg:
  name: KITTI2015
  root: data/kitti15
  train_list: datasets/kitti15/kitti15_train200.txt
  val_list: datasets/kitti15/kitti15_val35.txt
  test_list: datasets/kitti15/kitti15_test.txt
  num_workers: 8

  batch_uniform: false
  #  random_type: range
  #  w_range: [ 0.5, 2.0 ]
  #  h_range: [ 0.5, 2.0 ]
  #  random_type: choice
  #  h_range: [ 256, 288, 320, 352 ]
  #  w_range: [ 480, 512, 544, 576 ]

  transform:
    train:
      - type: RandomCrop
        size: [ 256, 512 ]
      #- type: RandomHorizontalFlip
      #  prob: 0.5
      - type: GetValidDisp
        max_disp: 192
      - type: TransposeImage
      - type: ToTensor
      - type: NormalizeImage
        mean: [ 0.485, 0.456, 0.406 ]
        std: [ 0.229, 0.224, 0.225 ]
    test:
      - type: StereoPad
        size: [ 384, 1248 ]
      - type: GetValidDisp
        max_disp: 192
      - type: TransposeImage
      - type: ToTensor
      - type: NormalizeImage
        mean: [ 0.485, 0.456, 0.406 ]
        std: [ 0.229, 0.224, 0.225 ]
    test_kitti:
      - type: DivisiblePad
        by: 16
      - type: TransposeImage
      - type: ToTensor
      - type: NormalizeImage
        mean: [ 0.485, 0.456, 0.406 ]
        std: [ 0.229, 0.224, 0.225 ]


model_cfg:
  model: PSMNet

  base_config:
    max_disp: 192

  # Backbone
  backbone_cfg:
    type: PSMNet

  # VolumeCostProcessor
  cost_processor_cfg:
    type: PSMCostProcessor

  # DispProcessor
  disp_processor_cfg:
    type: PSMDispProcessor


optimizer_cfg:
  solver: RMSprop
  lr: 0.0001

loss_cfg:
  - log_prefix: disp
    loss_term_weight: 1
    type: Weighted_Smooth_l1_Loss
    weights: [ 0.5, 0.7, 1.0 ]


scheduler_cfg:
  scheduler: MultiStepLR
  gamma: 0.1
  milestones: # Learning Rate Reduction at each milestones
    - 6000

  warmup:
    type: LinearWarmup
    warmup_period: 100

trainer_cfg:
  save_name: PSMNet_KITTI15
  restore_hint: 6600
  restore_ckpt_strict: true
  log_iter: 10
  with_test: true
  enable_float16: false
  save_iter: 200
  sync_BN: true
  total_iter: 20000
  total_epoch: 400
  optimizer_reset: false
  scheduler_reset: false
  clip_grad_norm:
    max_norm: 35
    norm_type: 2
  sampler:
    batch_shuffle: true
    batch_size: 7


evaluator_cfg:
  save_name: PSMNet_KITTI15
  eval_func: OpenStereoEvaluator
  restore_hint: 7000
  metric:
    - d1_all
    - epe
    - thres_1
    - thres_2
    - thres_3
  enable_float16: false
  restore_ckpt_strict: true
  show_progress_bar: false
  sampler:
    batch_shuffle: false
    batch_size: 1
