data_cfg:
  name: SceneFlow
  root: data/SceneFlow
  train_list: datasets/sceneflow/sceneflow_finalpass_train.txt
  val_list: datasets/sceneflow/sceneflow_finalpass_test.txt
  test_list: datasets/sceneflow/sceneflow_finalpass_test.txt
  num_workers: 8

  transform:
    train:
      - type: RandomCrop
        size: [ 256, 512 ]
      #- type: RandomHorizontalFlip
      #  prob: 0.5
      - type: GetValidDisp
        max_disp: 192
      - type: TransposeImage
      - type: ToTensor
      - type: NormalizeImage
        mean: [ 0.485, 0.456, 0.406 ]
        std: [ 0.229, 0.224, 0.225 ]
    test:
      - type: StereoPad
        size: [ 576, 960 ]
      - type: GetValidDisp
        max_disp: 192
      - type: TransposeImage
      - type: ToTensor
      - type: NormalizeImage
        mean: [ 0.485, 0.456, 0.406 ]
        std: [ 0.229, 0.224, 0.225 ]


model_cfg:
  model: GwcNet

  base_config:
    max_disp: 192
    downsample: 4
    num_groups: 40
    use_concat_volume: true
    concat_channels: 12

  # Backbone
  backbone_cfg:
    type: GwcNet

  # VolumeCostProcessor
  cost_processor_cfg:
    type: GwcVolumeCostProcessor

  # DispProcessor
  disp_processor_cfg:
    type: GwcDispProcessor


optimizer_cfg:
  solver: Adam
  lr: 0.001
  betas: [ 0.9, 0.999 ]


loss_cfg:
  - log_prefix: disp
    type: Weighted_Smooth_l1_Loss
    loss_term_weight: 1
    weights: [ 0.5,0.5,0.7,1.0 ]

scheduler_cfg:
  gamma: 0.5
  milestones: # Learning Rate Reduction at each milestones
    - 10000
    - 15000
    - 20000
    - 25000
  scheduler: MultiStepLR


trainer_cfg:
  save_name: GwcNet_SceneFlow
  restore_hint: 0
  restore_ckpt_strict: true
  log_iter: 10
  with_test: false
  enable_float16: false
  fix_BN: false
  save_iter: 2000
  sync_BN: true
  total_iter: 20000
  total_epoch: 20
  optimizer_reset: false
  scheduler_reset: false

  sampler:
    # type: DistributedSampler
    batch_shuffle: false
    batch_size: 4


evaluator_cfg:
  eval_func: OpenStereoEvaluator
  save_name: GwcNet_SceneFlow
  restore_hint: 0
  metric:
    - d1_all
    - epe
    - thres_1
    - thres_2
    - thres_3

  enable_float16: false
  restore_ckpt_strict: true

  sampler:
    type: BasicStereoSampler
    batch_shuffle: false
    batch_size: 1
